-- 코드를 입력하세요
WITH ranked AS(    
    SELECT *, 
    ROW_NUMBER() OVER(
    PARTITION BY FOOD_TYPE 
    ORDER BY FAVORITES DESC
    ) AS rnk
    FROM REST_INFO
)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM ranked
WHERE rnk = 1
ORDER BY FOOD_TYPE DESC;

