-- 코드를 입력하세요
SELECT 
    U.USER_ID,
    U.NICKNAME,
    CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소',
    CONCAT(
        SUBSTRING(U.TLNO, 1, 3), '-',
        SUBSTRING(U.TLNO, 4, 4), '-',
        SUBSTRING(U.TLNO, 8)
    ) AS '전화번호'
FROM USED_GOODS_BOARD AS B
INNER JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID
HAVING COUNT(B.BOARD_ID) >= 3
ORDER BY U.USER_ID DESC;