-- 코드를 입력하세요
SELECT CAR_ID , ROUND(AVG(DATEDIFF(END_DATE, START_DATE)) + 1, 1) AS AVERAGE_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    HAVING AVERAGE_DURATION >= 7 #GROUP를 한 후 평균을 구했으므로 HAVING절에 조건 적기
    ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;