-- 코드를 입력하세요
    SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT * P.PRICE) AS TOTAL_SALES
    FROM (
    SELECT *
    FROM FOOD_ORDER
    WHERE SUBSTRING(PRODUCE_DATE, 1, 7) = '2022-05' 
) AS O
    INNER JOIN FOOD_PRODUCT AS P ON P.PRODUCT_ID = O.PRODUCT_ID
    GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
    ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;