-- 코드를 작성해주세요  # 0과 1은 각각 1,2,3,4로 업그레이드가 가능
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY 
    FROM ITEM_INFO AS I
    INNER JOIN ITEM_TREE AS T ON I.ITEM_ID = T.ITEM_ID
    WHERE T.PARENT_ITEM_ID IN ( # parent ID가 0,1,3,4 인것을 뽑아야 함
    SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE'
    )
    ORDER BY I.ITEM_ID DESC;